### ISSUE TITLE
Add ncx page-map info

### ISSUE THREAD

**Issue by mikemccabe** [internetarchive/epub#1]
Investigate + maybe add Adobe page-map extension

**Comment by lizadaly** [comment]
Please no!  We'll never get rid of the thing.

There's a method in the NCX to do it already. Few reading systems support it yet, but the only thing that will make them do so is having 1 million+ epubs with it. :)  I'll support it in my system if I know it's in use.

These might be useful: 

http://groups.google.com/group/epubcheck/browse_thread/thread/352ee63fb6d82f35?pli=1

http://groups.yahoo.com/group/epub-community/message/160

http://www.epubbooks.com/blog/20081209/marking-up-page-numbers-in-the-epub-ncx/

**Comment by abdelazer** [comment]
My belief is that the ADE-implementors would be supportive of the correct, NCX-based approach if there was a critical mass of EPUBs in the wild using this technique.

Additionally, I'd strongly _discourage_ doing anything that would make IA-produced EPUBs invalid, as they should be used as a model for other EPUB creators.

**Comment by mikemccabe** [comment]
Changed issue title - I detect consensus on the best approach.

I've disabled my prototype page-map code for now.

**Comment by mikemccabe** [comment]
Checked in and more-or-less working!

Many thanks for the pointers - your examples were a huge help.
