### ISSUE TITLE
Error when generating epub book ensiminenvuosik00hakugoog

### ISSUE THREAD

**Issue by lizadaly** [internetarchive/epub#2]
I used the URL generation method; all I get back is "epub creation failed" so I can't be more helpful. :)

Maybe have it return a stack trace so at least we can report those directly in the ticket?  That might make it easier to identify the problems quickly.

**Comment by mikemccabe** [comment]
Fixed.

This book has .tif page images - teaching the converter about tif files did the trick.

The trace has path information, so we'll hold off on sharing it to the world for now :)
