### ISSUE TITLE
Epub creation takes too much memory

### ISSUE THREAD

**Issue by mikemccabe** [internetarchive/epub#29]
http://www.archive.org/details/rpertoireprati07grio - epub creation fails with ulimit 1048576.

command line:

ulimit -v 1048576; PATH=/petabox/sw/bin:$PATH LD_LIBRARY_PATH=/petabox/sw/lib/kakadu python ../epub/convert_iabook.py --epub --document=rpertoireprati07grio rpertoireprati07grio /9/items/rpertoireprati07grio rpertoir.epub 
zsh: segmentation fault  PATH=/petabox/sw/bin:$PATH LD_LIBRARY_PATH=/petabox/sw/lib/kakadu python   

... but it succeeds with ulimit 2097152.

**Comment by haase** [comment]
Thanks, that's helpful.  I'm wondering how to handle those cases for automatic generation.

-- Ken

**Comment by mikemccabe** [comment]
It turned out that I was failing to clear() the some pages returned by the lxml iterparse - critical, as they are VOLUMINOUS.  These were only the pages that weren't included in the final book (skipped, due to no addToAccessFormats) - but that was enough to kick memory usage over the edge for some books.

This was tricky to debug, as only occasional pages leaked.
