### ISSUE TITLE
"A general history of all voyages" failing epub creation

### ISSUE THREAD

**Issue by lizadaly** [internetarchive/epub#4]
http://www.archive.org/download/historyofvoyages00dupeuoft/historyofvoyages00dupeuoft.epub

**Comment by lizadaly** [comment]
Sometimes I get the 'failed epub creation' message, other times it downloads an epub, but it's missing its content:

$ unzip historyofvoyages00dupeuoft.epub  -d history
Archive:  historyofvoyages00dupeuoft.epub
 extracting: history/mimetype  
  inflating: history/META-INF/container.xml  
  inflating: history/OEBPS/stylesheet.css  
  inflating: history/OEBPS/page-template.xpgt

**Comment by mangtronix** [comment]
This book also fails epub creation: http://ia311031.us.archive.org/epub/index.php?id=cbatterybook306t00broo&dir=/0/items/cbatterybook306t00broo

**Comment by mangtronix** [comment]
That link came from the OPDS catalog generator.

**Comment by mikemccabe** [comment]
historyofvoyages has a book_id_abbyy._ZIP_ file, unlike everything else, which has a .gz.  Time to add another special case...

**Comment by mikemccabe** [comment]
Made a separate bug for cbatterybook, as it's likely to have a different cause.

**Comment by mikemccabe** [comment]
Fixed!
